apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: myresiliency
# similar to subscription and configuration specs, scopes lists the Dapr App IDs that this
# resiliency spec can be used by.
scopes:
  - carservice
  - worker
spec:
  # policies is where timeouts, retries and circuit breaker policies are defined.
  # each is given a name so they can be referred to from the targets section in the resiliency spec.
  policies:
    # timeouts are simple named durations.
    timeouts:
      general: 5s
      important: 60s
      largeResponse: 10s

    # retries are named templates for retry configurations and are instantiated for life of the operation.
    retries:
      pubsubRetry:
        policy: constant
        duration: 1s
        maxRetries: 10

      retryForever:
        policy: exponential
        maxInterval: 15s
        maxRetries: -1 # retry

    circuitBreakers:
      example:
        maxRequests: 1
        interval: 8s
        timeout: 45s
        trip: consecutiveFailures > 8



  targets:
    apps:
      carservice:
#        timeout: general
#        retry: retryForever
        circuitBreaker: example
          # circuit breakers for services are scoped app instance.
          # when a breaker is tripped, that route is removed from load balancing for the configured `timeout` duration.
#          circuitBreaker: simpleCB