apiVersion: apps/v1
kind: Deployment
metadata:
  name: carservice
  labels:
    app: carservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carservice
  template:
    metadata:
      labels:
        app: carservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/config: "config"
        dapr.io/app-id: "carservice"
        dapr.io/app-port: "8080"
        dapr.io/enable-app-health-check: "true"
        dapr.io/app-health-probe-interval: "3"
        dapr.io/app-health-probe-timeout: "200"
        dapr.io/app-health-threshold: "2"
    spec:
      containers:
        - name: carservice
          image: carservice
          env:
            - name: APP_PORT
              value: "8080"
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5